version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: asset_management
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5600:5432"
    networks:
      - asset-network

  backend:
    build:
      context: ./Backend
    container_name: Backend
    ports:
      - "3600:3600"
    depends_on:
      - postgres
    networks:
      - asset-network

  employee-asset:
    build:
      context: ./Employee-Asset
    container_name: Employee-Asset
    ports:
      - "8600:80"
    networks:
      - asset-network

  hr-asset:
    build:
      context: ./Hr Asset
    container_name: HR-Asset
    ports:
      - "8601:80"
    networks:
      - asset-network

volumes:
  postgres-data:

networks:
  asset-network:

